### ISSUE TITLE
What is this module for?

### ISSUE THREAD

**Issue by zeke** [parro-it/p-electron#1]
I saw this via https://github.com/parro-it/electron-localshortcut/pull/34. The README is a bit sparse. What does this module do?

**Comment by parro-it** [comment]
I built it to help with electron-localshortcut testing...
Some electron action are async but does not accept callback nor return promises. E.g. minify or close a window.

This module return a promise that resolve when the action is completed
I saw you look for this module failures on travis.I don't know why, it was working on my linux box 😁

Seems that minify event is not emitted on Travis...
